version: "3"
services:
  nginx-proxy:
    build:
      context: ./container/nginx-proxy
      dockerfile: Dockerfile
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
networks:
  default:
    external:
      name: nginx-proxy