FROM jwilder/nginx-proxy

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./conf.d/ /etc/nginx/conf.d/
COPY ./503.html /usr/share/nginx/html/503.html
COPY ./lebowski.gif /usr/share/nginx/html/lebowski.gif